### ISSUE TITLE
SequelizeDatabaseError: relation "disposals" does not exist

### ISSUE THREAD

**Issue by mikinty** [amacneil/cryptogains#44]
I think I followed all the instructions in the repo, but ran into the following error

(Using WSL)

Full stack trace:

```
> dbmate up      
Writing: ./db/schema.sql
> node app.js

Truncate gains
(node:50) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
SequelizeDatabaseError: relation "disposals" does not exist
    at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
    at Result.<anonymous> (/app/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
    at Result.emit (events.js:314:20)
    at Result.Query.handleError (/app/node_modules/pg/lib/query.js:163:8)
    at Client.<anonymous> (/app/node_modules/pg/lib/client.js:188:26)
    at Connection.emit (events.js:314:20)
    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:133:12)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
From previous event:
    at Query.run (/app/node_modules/sequelize/lib/dialects/postgres/query.js:74:17)
    at /app/node_modules/sequelize/lib/sequelize.js:849:20
    at /app/node_modules/retry-as-promised/index.js:39:21
From previous event:
    at retryAsPromised (/app/node_modules/retry-as-promised/index.js:29:10)
    at ConnectionManager.<anonymous> (/app/node_modules/sequelize/lib/sequelize.js:848:12)
From previous event:
    at Promise.then (/app/node_modules/sequelize/lib/promise.js:21:17)
    at Model.destroy (/app/node_modules/sequelize/lib/model.js:2300:6)
    at Model.truncate (/app/node_modules/sequelize/lib/model.js:2237:15)
    at truncateGains (/app/src/calculategains.js:368:18)
    at main (/app/app.js:64:9)
    at Object.<anonymous> (/app/app.js:72:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by amacneil** [comment]
Since it says `SequelizeDatabaseError: relation "disposals" does not exist`, I don't think the `dbmate up` worked. Or, maybe it created a database but then nodejs connected to a different database?
